site_name: Packages Test Documentation
site_url: https://roblox.github.io/packages-test/
repo_name: Roblox/packages-test
repo_url: https://github.com/Roblox/packages-test

theme:
  name: material
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

pages:
  - Home: index.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences