[package]
name = "zotethemighty/packages-test"
author = "ZoteTheMighty"
license = ""
version = "1.1.2"

[dependencies]
Roact = { name = "roblox/roact", version = "1.0", registry = "https://github.com" }
