name = "zotethemighty/packages-test"
author = "ZoteTheMighty"
license = ""
version = "1.1.0"

[dependencies]
Roact = { git = "https://github.com/Roblox/roact.git" }
Rodux = { git = "https://github.com/Roblox/rodux.git", rev = "abe28472" }
TestEZ = { git = "https://github.com/Roblox/testez.git" }
RoactRodux = { git = "https://github.com/Roblox/roact-rodux.git", rev = "v1.0.0-pre2" }
