name = "TableButton"
author = "ZoteTheMighty"
license = ""
version = "0.1.0"
content_root = "src"

[dependencies]
FlipTable = { git = "https://github.com/ZoteTheMighty/packages-test", rev = "LibFlipTable" }
PrintButton = { git = "https://github.com/ZoteTheMighty/packages-test", rev = "LibPrintButton" }